[project]
name = "simple-merge-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pypdf>=6.2.0",
    "tkinterdnd2>=0.4.3",
]
